INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, MIDDLE_INITIAL, ADDRESS_ID)
VALUES ('Joe', 'Biden', 'C', 2);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, MIDDLE_INITIAL, ADDRESS_ID)
VALUES ('Donald', 'Trump', 'J', 1);